services:
  mysql:
    image: mysql:8
    container_name: produtos_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: db_produtos
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p12345678"]
      interval: 10s
      timeout: 5s
      retries: 10

  app:
    build: .
    container_name: produtos_app
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: 12345678
      DB_NAME: db_produtos
      PORT: 5000
    ports:
      - "5000:5000"

volumes:
  mysql_data:
