name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: 12345678
          MYSQL_DATABASE: db_produtos
        ports:
          - 3306:3306

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: pip install -r requirements.txt

      - name: Instalar MySQL client
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-client

      - name: Criar banco
        run: |
          sleep 20
          mysql -h 127.0.0.1 -u root -p12345678 < init.sql

      - name: Rodar testes
        run: pytest -v
